- title: "Caratula"
  alias: Caratula
  skip_title: true

- title: Registro de Versiones del Informe
  alias: versions

- title: Project Report Collaboration Insights
  alias: Insights

- title: Contenido
  children:
    - title: Tabla de contenidos
      alias: index

- title: Student Outcome
  alias: outcome

- title: "Capítulo I: Introducción"
  alias: capitulo 1
  children:
    - title: "1.1. Startup Profile"
      alias: startup
      children:
        - title: "1.1.1. Descripción de la Startup"
          alias: description
        - title: "1.1.2. Perfiles de integrantes del equipo"
          alias: team members
    - title: "1.2. Solution Profile"
      alias: solution
      children:
        - title: "1.2.1. Antecedentes y problemática"
          alias: antecedentes
        - title: "1.2.2. Lean UX Process"
          alias: lean ux process
          skip_after: false
          has_intro: true
          children:
            - title: "1.2.2.1. Lean UX Problem Statements"
              alias: problem statements
              skip_after: false
            - title: "1.2.2.2. Lean UX Assumptions"
              alias: assumptions
              skip_after: false
            - title: "1.2.2.3. Lean UX Hypothesis Statements"
              alias: hypothesis statements
              skip_after: false
            - title: "1.2.2.4. Lean UX Canvas"
              alias: canvas
    - title: "1.3. Segmentos objetivo"
      alias: segments

- title: "Capítulo II: Requirements Elicitation & Analysis"
  alias: capitulo 2
  children:
    - title: "2.1. Competidores"
      alias: competitors
      children:
        - title: "2.1.1. Análisis competitivo"
          alias: competitive analysis
          skip_after: false
        - title: "2.1.2. Estrategias y tácticas frente a competidores"
          alias: competitive strategy
    - title: "2.2. Entrevistas"
      alias: interviews
      has_intro: true
      children:
        - title: "2.2.1. Diseño de entrevistas"
          alias: interview design
        - title: "2.2.2. Registro de entrevistas"
          alias: interview registry
        - title: "2.2.3. Análisis de entrevistas"
          alias: interview analysis
    - title: "2.3. Needfinding"
      alias: needfinding
      children:
        - title: "2.3.1. User Personas"
          alias: personas
        - title: "2.3.2. User Task Matrix"
          alias: task matrix
          skip_after: true
        - title: "2.3.3. User Journey Mapping"
          alias: journey mapping
        - title: "2.3.4. Empathy Mapping"
          alias: empathy mapping
    - title: "2.4. Big Picture EventStoring"
      alias: eventstoring
    - title: "2.5. Ubiquitous Language"
      alias: ubiquitous language

- title: "Capítulo III: Requirements Specification"
  alias: capitulo 3
  children:
    - title: "3.1. User Stories"
      alias: user stories
    - title: "3.2. Impact Mapping"
      alias: impact mapping
    - title: "3.3. Product Backlog"
      alias: product backlog

- title: "Capítulo IV: Product Design"
  alias: capitulo 4
  children:
    - title: "4.1. Style Guidelines"
      alias: style guidelines
      children:
        - title: "4.1.1. General Style Guidelines"
          alias: general style
          skip_after: true
        - title: "4.1.2. Web Style Guidelines"
          alias: web style
    - title: "4.2. Information Architecture"
      alias: architecture
      has_intro: false
      children:
        - title: "4.2.1. Organization Systems"
          alias: organization
          skip_after: false
        - title: "4.2.2. Labeling Systems"
          alias: labeling
          skip_after: false
        - title: "4.2.3. SEO Tags and Meta Tags"
          alias: seo
          skip_after: false
        - title: "4.2.4. Searching Systems"
          alias: searching
          skip_after: false
        - title: "4.2.5. Navigation Systems"
          alias: navigation
    - title: "4.3. Landing Page UI Design"
      alias: landing design
      children:
        - title: "4.3.1. Landing Page Wireframe"
          alias: landing wireframe
        - title: "4.3.2. Landing Page Mock-up"
          alias: landing mockup
    - title: "4.4. Web Applications UX/UI Design"
      alias: apps design
      children:
        - title: "4.4.1. Web Applications Wireframes"
          alias: app wireframes
        - title: "4.4.2. Web Applications Wireflow Diagrams"
          alias: wireflows
        - title: "4.4.2. Web Applications Mock-ups"
          alias: app mockups
        - title: "4.4.3. Web Applications User Flow Diagrams"
          alias: userflows
    - title: "4.5. Web Applications Prototyping"
      alias: prototyping
    - title: "4.6. Domain-Driven Software Architecture"
      alias: software architecture
      children:
        - title: "4.6.1. Design-Level EventStorming"
          alias: design eventstorming
        - title: "4.6.2. Software Architecture Context Diagram"
          alias: context diagram
        - title: "4.6.3. Software Architecture Container Diagrams"
          alias: container diagrams
        - title: "4.6.4. Software Architecture Components Diagrams"
          alias: component diagrams
    - title: "4.7. Software Object-Oriented Design"
      alias: oop
      children:
        - title: "4.7.1. Class Diagrams"
          alias: class diagrams
    - title: "4.8. Database Design"
      alias: database
      children:
        - title: "4.8.1. Database Diagram"
          alias: db diagram

- title: "Capítulo V: Product Implementation, Validation & Deployment"
  alias: capitulo 5
  skip_after: false
  has_intro: true
  children:
    - title: "5.1. Software Configuration Management"
      alias: scm
      children:
        - title: "5.1.1. Software Development Environment Configuration"
          alias: dev environment
        - title: "5.1.2. Source Code Management"
          alias: git config
        - title: "5.1.3. Source Code Style Guide & Conventions"
          alias: code style
        - title: "5.1.4. Software Deployment Configuration"
          alias: deployment config
    - title: "5.2. Landing Page, Services & Applications Implementation"
      alias: implementation
      children:
        - title: "5.2.1. Sprint Backlogs"
          alias: sprint backlogs
          has_intro: true
          children:
            - title: "5.2.1.1. Sprint Backlog 1"
              alias: sprint backlog 1
            - title: "5.2.1.2. Sprint Backlog 2"
              alias: sprint backlog 2
            - title: "5.2.1.3. Sprint Backlog 3"
              alias: sprint backlog 3
            - title: "5.2.1.4. Sprint Backlog 4"
              alias: sprint backlog 4
        - title: "5.2.2. Implemented Landing Page Evidence"
          alias: implemented landing page evidence
        - title: "5.2.3. Implemented Frontend-Web Application Evidence"
          alias: implemented frontend web application evidence
        - title: "5.2.4. Acuerdo de Servicio - SaaS"
          alias: acuerdo de servicio saas
        - title: "5.2.5. Implemented Native-Mobile Application Evidence"
          alias: implemented native mobile application evidence
        - title: "5.2.6. Implemented RESTful API and/or Serverless Backend Evidence"
          alias: implemented restful api serverless backend evidence
        - title: "5.2.7. RESTful API documentation"
          alias: restful api documentation
        - title: "5.2.8. Team Collaboration Insights"
          alias: team collaboration insights
    - title: "5.3. Validation Interviews"
      alias: validation
      children:
        - title: "5.3.1. Diseño de entrevistas"
          alias: design
        - title: "5.3.2. Registro de entrevistas"
          alias: registry
        - title: "5.3.3. Evaluaciones según heurísticas"
          alias: heuristics
    - title: "5.4. Video About the Product"
      alias: product video

- title: "Capítulo VI: Product Verification & Validation"
  alias: capitulo 6
  children:
    - title: "6.1. Testing Suites & Validation"
      alias: testing suites
      children:
        - title: "6.1.1. Core Entities Unit Tests"
          alias: unit tests
        - title: "6.1.2. Core Integration Tests"
          alias: integration tests
        - title: "6.1.3. Core Behavior-Driven Development"
          alias: bdd
        - title: "6.1.4. Core System Tests"
          alias: system tests

    - title: "6.2. Static Testing & Verification"
      alias: static testing
      children:
        - title: "6.2.1. Static Code Analysis"
          alias: static code analysis
          children:
            - title: "6.2.1.1. Coding Standards & Code Conventions"
              alias: coding standards
            - title: "6.2.1.2. Code Quality & Code Security"
              alias: code quality security
        - title: "6.2.2. Reviews"
          alias: reviews

    - title: "6.3. Validation Interviews"
      alias: validation interviews
      children:
        - title: "6.3.1. Interview Design"
          alias: interview design
        - title: "6.3.2. Interview Records"
          alias: interview records
        - title: "6.3.3. Heuristic Evaluations"
          alias: heuristic evaluations

    - title: "6.4. User Experience Audit"
      alias: ux audit
      children:
        - title: "6.4.1. Audit Performed"
          alias: audit performed
          children:
            - title: "6.4.1.1. Audited Group Information"
              alias: audited group info
            - title: "6.4.1.2. Audit Schedule"
              alias: audit schedule
            - title: "6.4.1.3. Audit Content"
              alias: audit content
        - title: "6.4.2. Audit Received"
          alias: audit received
          children:
            - title: "6.4.2.1. Auditor Group Information"
              alias: auditor group info
            - title: "6.4.2.2. Received Audit Schedule"
              alias: received audit schedule
            - title: "6.4.2.3. Received Audit Content"
              alias: received audit content
            - title: "6.4.2.4. Summary of Modifications to Address Findings"
              alias: findings summary

- title: "Capítulo VII: DevOps Practices"
  alias: capitulo 7
  children:
    - title: "7.1. Continuous Integration"
      alias: ci
      children:
        - title: "7.1.1. Tools and Practices"
          alias: tools ci
        - title: "7.1.2. Build & Test Suite Pipeline Components"
          alias: pipeline ci

    - title: "7.2. Continuous Delivery"
      alias: cd
      children:
        - title: "7.2.1. Tools and Practices"
          alias: tools cd
        - title: "7.2.2. Stages Deployment Pipeline Components"
          alias: pipeline cd

    - title: "7.3. Continuous Deployment"
      alias: cdep
      children:
        - title: "7.3.1. Tools and Practices"
          alias: tools cdep
        - title: "7.3.2. Production Deployment Pipeline Components"
          alias: pipeline cdep

    - title: "7.4. Continuous Monitoring"
      alias: cmonit
      children:
        - title: "7.4.1. Tools and Practices"
          alias: monitoring tools
        - title: "7.4.2. Monitoring Pipeline Components"
          alias: monitoring pipeline
        - title: "7.4.3. Alerting Pipeline Components"
          alias: alerting pipeline
        - title: "7.4.4. Notification Pipeline Components"
          alias: notification pipeline

- title: "Capítulo VIII: Experiment-Driven Development"
  alias: capitulo 8
  children:
    - title: "8.1. Experiment Planning"
      alias: EP
      children:
        - title: "8.1.1. As-Is Summary"
          alias: as is summary
        - title: "8.1.2. Raw Material: Assumptions, Knowledge Gaps, Ideas, Claims"
          alias: raw material
        - title: "8.1.3. Experiment-Ready Questions"
          alias: experiment questions
        - title: "8.1.4. Question Backlog"
          alias: question backlog
        - title: "8.1.5. Experiment Cards"
          alias: experiment cards

    - title: "8.2. Experiment Design"
      alias: ED
      children:
        - title: "8.2.1. Hypotheses"
          alias: hypotheses
        - title: "8.2.2. Domain Business Metrics"
          alias: business metrics
        - title: "8.2.3. Measures"
          alias: measures
        - title: "8.2.4. Conditions"
          alias: conditions
        - title: "8.2.5. Scale Calculations and Decisions"
          alias: scale calculations
        - title: "8.2.6. Methods Selection"
          alias: methods selection
        - title: "8.2.7. Data Analytics: Goals, KPIs and Metrics Selection"
          alias: analytics goals
        - title: "8.2.8. Web and Mobile Tracking Plan"
          alias: tracking plan

    - title: "8.3. Experimentation"
      alias: Exp
      children:
        - title: "8.3.1. To-Be User Stories"
          alias: user stories
        - title: "8.3.2. To-Be Product Backlog"
          alias: backlog
        - title: "8.3.3. Pipeline-supported, Experiment-Driven To-Be Software Platform Lifecycle"
          alias: lifecycle
          children:
            - title: "8.3.3.1. To-Be Sprint Backlogs"
              alias: to-be sprint backlogs
            - title: "8.3.3.2. Implemented To-Be Landing Page Evidence"
              alias: landing page evidence
            - title: "8.3.3.3. Implemented To-Be Frontend-Web Application Evidence"
              alias: frontend evidence
            - title: "8.3.3.4. Implemented To-Be Native-Mobile Application Evidence"
              alias: mobile evidence
            - title: "8.3.3.5. Implemented To-Be RESTful API and/or Serverless Backend Evidence"
              alias: api evidence
            - title: "8.3.3.6. Team Collaboration Insights"
              alias: collaboration insights
        - title: "8.3.4. To-Be Validation Interviews"
          alias: to-be validation interviews
          children:
            - title: "8.3.4.1. Diseño de Entrevistas"
              alias: interview design
            - title: "8.3.4.2. Registro de Entrevistas"
              alias: interview records

    - title: "8.4. Experiment Aftermath & Analysis"
      alias: aftermath
      children:
        - title: "8.4.1. Analysis and Interpretation of Results"
          alias: analysis results
        - title: "8.4.2. Re-scored and Re-prioritized Question Backlog"
          alias: question backlog reprioritized

    - title: "8.5. Continuous Learning"
      alias: continuous learning
      children:
        - title: "8.5.1. Shareback Session Artifacts: Learning Workflow"
          alias: shareback session

    - title: "8.6. To-Be Software Platform Pre-launch"
      alias: prelaunch
      children:
        - title: "8.6.1. About-the-Product Intro Video"
          alias: intro video

- title: "Matriz de Evaluación Ética y de Impacto"
  alias: ethics matrix

- title: "Conclusiones"
  alias: conclusions

- title: "Bibliografía"
  alias: bibliography

- title: "Anexos"
  alias: annexes